#
# Main targets.
#
# The fact that you must include at least one concrete implementation
# is not captured here. You must only edit the dependencies.
#
m4/enabled.m4.tmp: | delete_main_targets verificatum
	@cat m4/raw_enabled.m4 | sort > m4/enabled.m4.tmp
	@echo "Generate enabling M4 macros in m4/enabled.m4.tmp."
m4/test_enabled.m4.tmp: | delete_main_targets test_verificatum
	@cat m4/raw_enabled.m4 | sort > m4/test_enabled.m4.tmp
	@echo "Generate enabling M4 macros in m4/test_enabled.m4.tmp."
#
# Commonly modified targets.
#
arithm: ec ECqPGroup ExpHom FixModPow Hom ModPGroup ModPowProd PField PGroup PPGroup PPRing PRing
	@./tools/enable verificatum/arithm/arithm.js m4/raw_enabled.m4
crypto: ElGamal ElGamalZKPoK ElGamalZKPoKAdapter ElGamalZKPoKWriteIn SchnorrProof SigmaProof SigmaProofAnd SigmaProofOr SigmaProofPara ZKPoK ZKPoKWriteIn ZKPoKWriteInAdapter
	@./tools/enable verificatum/crypto/crypto.js m4/raw_enabled.m4
curves: brainpoolp192r1 brainpoolp224r1 brainpoolp256r1 brainpoolp320r1 brainpoolp384r1 brainpoolp512r1 P-192 P-224 P-256 P-384 P-521 prime192v1 prime192v2 prime192v3 prime239v1 prime239v3 prime256v1 secp192k1 secp192r1 secp224k1 secp224r1 secp256k1 secp256r1 secp384r1 secp521r1
	@./tools/enable verificatum/arithm/ECqPGroup_named_curves.js m4/raw_enabled.m4
ECqPGroup: curves ec PField PGroup
	@./tools/enable verificatum/arithm/ECqPGroup.js m4/raw_enabled.m4
groups: modp1024 modp1536 modp2048 modp3072 modp4096 modp6144 modp768 modp8192
	@./tools/enable verificatum/arithm/ModPGroup_named_groups.js m4/raw_enabled.m4

test_arithm: test_ECqPGroup test_FixModPow test_LargeInteger test_li test_ModPGroup test_ModPowProd test_PField test_PGroup test_PPGroup test_PPRing test_PRing
	@./tools/enable verificatum/arithm/test_arithm.js m4/raw_enabled.m4
test_crypto: test_ElGamal test_ElGamalZKPoKWriteIn test_SchnorrProof test_SigmaProof test_SigmaProofAnd test_SigmaProofOr
	@./tools/enable verificatum/crypto/test_crypto.js m4/raw_enabled.m4
test_verificatum: dev test_arithm test_arithm test_crypto test_crypto test_eio test_util verificatum
	@./tools/enable verificatum/test_verificatum.js m4/raw_enabled.m4

#
# Other modifiable targets:
#
ElGamal: PPGroup PPRing
	@./tools/enable verificatum/crypto/ElGamal.js m4/raw_enabled.m4
ElGamalZKPoKAdapter: ZKPoK
	@./tools/enable verificatum/crypto/ElGamalZKPoKAdapter.js m4/raw_enabled.m4
ElGamalZKPoK: ElGamal ElGamalZKPoKAdapter
	@./tools/enable verificatum/crypto/ElGamalZKPoK.js m4/raw_enabled.m4
ElGamalZKPoKWriteIn: ElGamal ZKPoKWriteInAdapter
	@./tools/enable verificatum/crypto/ElGamalZKPoKWriteIn.js m4/raw_enabled.m4
ExpHom: Hom
	@./tools/enable verificatum/arithm/ExpHom.js m4/raw_enabled.m4
FixModPow: ModPowProd
	@./tools/enable verificatum/arithm/FixModPow.js m4/raw_enabled.m4
Hom: PField PGroup
	@./tools/enable verificatum/arithm/Hom.js m4/raw_enabled.m4
ModPGroup: groups LargeInteger PField PGroup
	@./tools/enable verificatum/arithm/ModPGroup.js m4/raw_enabled.m4
ModPowProd: LargeInteger
	@./tools/enable verificatum/arithm/ModPowProd.js m4/raw_enabled.m4
PField: LargeInteger PRing
	@./tools/enable verificatum/arithm/PField.js m4/raw_enabled.m4
PPGroup: PGroup
	@./tools/enable verificatum/arithm/PPGroup.js m4/raw_enabled.m4
PPRing: PRing
	@./tools/enable verificatum/arithm/PPRing.js m4/raw_enabled.m4
SchnorrProof: ExpHom SigmaProof
	@./tools/enable verificatum/crypto/SchnorrProof.js m4/raw_enabled.m4
SigmaProofAnd: SigmaProofPara
	@./tools/enable verificatum/crypto/SigmaProofAnd.js m4/raw_enabled.m4
SigmaProofPara: SigmaProof
	@./tools/enable verificatum/crypto/SigmaProofPara.js m4/raw_enabled.m4
SigmaProof: ZKPoK
	@./tools/enable verificatum/crypto/SigmaProof.js m4/raw_enabled.m4
verificatum: arithm benchmark crypto
	@./tools/enable verificatum/verificatum.js m4/raw_enabled.m4
ZKPoKWriteInAdapter: ZKPoKWriteIn
	@./tools/enable verificatum/crypto/ZKPoKWriteInAdapter.js m4/raw_enabled.m4
ZKPoKWriteIn: ElGamalZKPoKAdapter ExpHom SchnorrProof
	@./tools/enable verificatum/crypto/ZKPoKWriteIn.js m4/raw_enabled.m4

test_ECqPGroup: ECqPGroup test_PGroup
	@./tools/enable verificatum/arithm/test_ECqPGroup.js m4/raw_enabled.m4
test_ElGamal: ElGamal
	@./tools/enable verificatum/crypto/test_ElGamal.js m4/raw_enabled.m4
test_ElGamalZKPoKWriteIn: ElGamalZKPoKWriteIn
	@./tools/enable verificatum/crypto/test_ElGamalZKPoKWriteIn.js m4/raw_enabled.m4
test_FixModPow: FixModPow
	@./tools/enable verificatum/arithm/test_FixModPow.js m4/raw_enabled.m4
test_ModPGroup: ModPGroup test_PGroup
	@./tools/enable verificatum/arithm/test_ModPGroup.js m4/raw_enabled.m4
test_ModPowProd: ModPowProd
	@./tools/enable verificatum/arithm/test_ModPowProd.js m4/raw_enabled.m4
test_PField: PField test_PRing
	@./tools/enable verificatum/arithm/test_PField.js m4/raw_enabled.m4
test_PGroup: PGroup
	@./tools/enable verificatum/arithm/test_PGroup.js m4/raw_enabled.m4
test_PPGroup: PPGroup test_PGroup
	@./tools/enable verificatum/arithm/test_PPGroup.js m4/raw_enabled.m4
test_PPRing: PPRing test_PRing
	@./tools/enable verificatum/arithm/test_PPRing.js m4/raw_enabled.m4
test_PRing: PRing
	@./tools/enable verificatum/arithm/test_PRing.js m4/raw_enabled.m4
test_SchnorrProof: SchnorrProof
	@./tools/enable verificatum/crypto/test_SchnorrProof.js m4/raw_enabled.m4
test_SigmaProofAnd: SigmaProofAnd
	@./tools/enable verificatum/crypto/test_SigmaProofAnd.js m4/raw_enabled.m4
test_SigmaProofOr: SigmaProofOr
	@./tools/enable verificatum/crypto/test_SigmaProofOr.js m4/raw_enabled.m4
test_SigmaProof: SigmaProof
	@./tools/enable verificatum/crypto/test_SigmaProof.js m4/raw_enabled.m4

#
# DO NOT EDIT THE FOLLOWING ENTRIES!
#
benchmark:
	@./tools/enable verificatum/benchmark/benchmark.js m4/raw_enabled.m4
brainpoolp192r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_brainpoolp192r1.js m4/raw_enabled.m4
brainpoolp224r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_brainpoolp224r1.js m4/raw_enabled.m4
brainpoolp256r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_brainpoolp256r1.js m4/raw_enabled.m4
brainpoolp320r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_brainpoolp320r1.js m4/raw_enabled.m4
brainpoolp384r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_brainpoolp384r1.js m4/raw_enabled.m4
brainpoolp512r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_brainpoolp512r1.js m4/raw_enabled.m4
dev:
	@./tools/enable verificatum/dev/dev.js m4/raw_enabled.m4
ec:
	@./tools/enable verificatum/arithm/ec.js m4/raw_enabled.m4
LargeInteger:
	@./tools/enable verificatum/arithm/LargeInteger.js m4/raw_enabled.m4
modp1024:
	@./tools/enable verificatum/arithm/ModPGroup_named_modp1024.js m4/raw_enabled.m4
modp1536:
	@./tools/enable verificatum/arithm/ModPGroup_named_modp1536.js m4/raw_enabled.m4
modp2048:
	@./tools/enable verificatum/arithm/ModPGroup_named_modp2048.js m4/raw_enabled.m4
modp3072:
	@./tools/enable verificatum/arithm/ModPGroup_named_modp3072.js m4/raw_enabled.m4
modp4096:
	@./tools/enable verificatum/arithm/ModPGroup_named_modp4096.js m4/raw_enabled.m4
modp6144:
	@./tools/enable verificatum/arithm/ModPGroup_named_modp6144.js m4/raw_enabled.m4
modp768:
	@./tools/enable verificatum/arithm/ModPGroup_named_modp768.js m4/raw_enabled.m4
modp8192:
	@./tools/enable verificatum/arithm/ModPGroup_named_modp8192.js m4/raw_enabled.m4
P-192:
	@./tools/enable verificatum/arithm/ECqPGroup_named_P-192.js m4/raw_enabled.m4
P-224:
	@./tools/enable verificatum/arithm/ECqPGroup_named_P-224.js m4/raw_enabled.m4
P-256:
	@./tools/enable verificatum/arithm/ECqPGroup_named_P-256.js m4/raw_enabled.m4
P-384:
	@./tools/enable verificatum/arithm/ECqPGroup_named_P-384.js m4/raw_enabled.m4
P-521:
	@./tools/enable verificatum/arithm/ECqPGroup_named_P-521.js m4/raw_enabled.m4
PGroup:
	@./tools/enable verificatum/arithm/PGroup.js m4/raw_enabled.m4
prime192v1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_prime192v1.js m4/raw_enabled.m4
prime192v2:
	@./tools/enable verificatum/arithm/ECqPGroup_named_prime192v2.js m4/raw_enabled.m4
prime192v3:
	@./tools/enable verificatum/arithm/ECqPGroup_named_prime192v3.js m4/raw_enabled.m4
prime239v1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_prime239v1.js m4/raw_enabled.m4
prime239v3:
	@./tools/enable verificatum/arithm/ECqPGroup_named_prime239v3.js m4/raw_enabled.m4
prime256v1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_prime256v1.js m4/raw_enabled.m4
PRing:
	@./tools/enable verificatum/arithm/PRing.js m4/raw_enabled.m4
secp192k1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_secp192k1.js m4/raw_enabled.m4
secp192r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_secp192r1.js m4/raw_enabled.m4
secp224k1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_secp224k1.js m4/raw_enabled.m4
secp224r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_secp224r1.js m4/raw_enabled.m4
secp256k1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_secp256k1.js m4/raw_enabled.m4
secp256r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_secp256r1.js m4/raw_enabled.m4
secp384r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_secp384r1.js m4/raw_enabled.m4
secp521r1:
	@./tools/enable verificatum/arithm/ECqPGroup_named_secp521r1.js m4/raw_enabled.m4
SigmaProofOr:
	@./tools/enable verificatum/crypto/SigmaProofOr.js m4/raw_enabled.m4
test_eio:
	@./tools/enable verificatum/eio/test_eio.js m4/raw_enabled.m4
test_LargeInteger:
	@./tools/enable verificatum/arithm/test_LargeInteger.js m4/raw_enabled.m4
test_li:
	@./tools/enable verificatum/arithm/test_li.js m4/raw_enabled.m4
test_util:
	@./tools/enable verificatum/util/test_util.js m4/raw_enabled.m4
ZKPoK:
	@./tools/enable verificatum/crypto/ZKPoK.js m4/raw_enabled.m4
#
# This is a hack to get something more robust than .PHONY.
#
delete_main_targets:
	@rm -f m4/raw_enabled.m4
