#!/bin/sh

# Copyright 2008-2018 Douglas Wikstrom
#
# This file is part of Verificatum JavaScript Cryptographic library
# (VJSC).
#
# VJSC is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# VJSC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General
# Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with VJSC. If not, see <http://www.gnu.org/licenses/>.


# This script runs "make check" for every valid wordsize.

WORDSIZES=`seq 8 2 30`

DELIM="#############################################################"

for WORDSIZE in ${WORDSIZES};
do
    
    printf "\n%s\n\n" ${DELIM}
    make clean
    make test_vjsc WORDSIZE=${WORDSIZE}
    make check 
    
done
