#!/bin/sh

# Copyright 2008-2019 Douglas Wikstrom
#
# This file is part of Verificatum JavaScript Cryptographic library
# (VJSC).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Compiles multiple fragments of JavaScript code into a single file
# using M4 macros. Redundant copyright headers are removed and the
# file is reformatted and indented.

SCRIPTPATH=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPTPATH")

TMP_DIR=${1}
M4FILTER=${2}
HEADER=${3}
JSSRC=${4}
INPUTS="${5}"
OUTPUT=${6}

if test ${1} = "-h";
then

    printf "Usage:\n"
    printf "${0} <tmp dir> <header> <js source dir> <inputs> <output>\n\n"

else

    # Make temporary directory.
    mkdir -p ${TMP_DIR}/${OUTPUT%/*}

    # Combine all necessary files using M4 into a single file and
    # apply M4 macros.
    cat ${M4FILTER} "${INPUTS}" | m4 > ${TMP_DIR}/${OUTPUT}_headers

    # Strip all license headers and replace them by a single license
    # header at the top of the compiled file.

    # Remove all headers, kill spurious new lines, and add proper newlines.
    HEADER_STRING=`cat ${JSSRC}/AGPL_3.0_HEADER.js | tr "\n" "\f" | sed "s/\f/\\\\f/g"`
    cat ${TMP_DIR}/${OUTPUT}_headers \
| sed "s/^\s*//g" \
| tr "\n" "\f" \
| sed "s/^\f\f*//" \
| sed "s|${HEADER_STRING}||g" \
| sed "s/\f\f\f*/\f\f/g" \
| sed "s|\(\f\f// #*\f//\)|\f\1|g" \
| sed "s/,\s\s*}/\f}/g" \
| tr "\f" "\n" > ${TMP_DIR}/${OUTPUT}_no_headers

    # Put back a single header at the top.
    cat ${HEADER} ${TMP_DIR}/${OUTPUT}_no_headers > ${TMP_DIR}/${OUTPUT}_header

    # Indent file in place.
    ${SCRIPTDIR}/indent-file ${TMP_DIR}/${OUTPUT}_header

    # Use this file as it is with indentation and comments.
    cp ${TMP_DIR}/${OUTPUT}_header ${OUTPUT}

    # Clean up temporary files.
    rm -rf ${TMP_DIR}
fi
