#!/bin/sh

# Copyright 2008-2020 Douglas Wikstrom
#
# This file is part of Verificatum JavaScript Cryptographic library
# (VJSC).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Extracts the list of dependencies of all files listed in the BASIC
# parameter and outputs them on EXPANDED.

TMP_DIR=${1}
ROOT=${2}
BASIC=${3}
EXPANDED=${4}

FILES=`cat ${BASIC}`

mkdir -p ${TMP_DIR}
for FILE in ${FILES};
do
    cat ${ROOT}/${FILE} \
| grep -E "M4_NEEDS|M4_INCLUDEOPT" \
| sed "s/M4_NEEDS(//" \
| sed "s/M4_INCLUDEOPT(//" \
| sed "s/)dnl//" \
>> ${TMP_DIR}/blowup
done

cat ${TMP_DIR}/blowup | sort | uniq > ${EXPANDED}
