#!/bin/sh

# Copyright 2008-2020 Douglas Wikstrom
#
# This file is part of Verificatum JavaScript Cryptographic library
# (VJSC).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Recursively expands all dependencies of the files in the root
# directory.

SCRIPTPATH=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPTPATH")

TMP_DIR=${1}
ROOT=${2}
NEEDS=${3}

GET_DIR=${TMP_DIR}/getneeds
mkdir -p ${GET_DIR}
EXP_DIR=${TMP_DIR}/expandneeds
mkdir -p ${EXP_DIR}

# Start with all files.
rm -f ${GET_DIR}/newneeds
touch ${GET_DIR}/newneeds
find ${ROOT} | grep "\.js" | sed "s|${ROOT}/||" > ${GET_DIR}/oldneeds

# Expand.
DIFF=1
while !( test ${DIFF} = 0 );
do
    ${SCRIPTDIR}/expandneeds ${EXP_DIR} ${ROOT} ${GET_DIR}/oldneeds ${GET_DIR}/newneeds

    # Swap oldneeds and newneeds
    mv ${GET_DIR}/oldneeds ${GET_DIR}/tmpneeds
    mv ${GET_DIR}/newneeds ${GET_DIR}/oldneeds
    mv ${GET_DIR}/tmpneeds ${GET_DIR}/newneeds

    DIFF=`diff ${GET_DIR}/newneeds ${GET_DIR}/oldneeds | wc -l`
done

mv ${GET_DIR}/oldneeds ${NEEDS}

rm -rf ${GET_DIR} ${EXP_DIR}
