#!/bin/sh

# Copyright 2008-2019 Douglas Wikstrom
#
# This file is part of Verificatum JavaScript Cryptographic library
# (VJSC).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

SCRIPTPATH=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPTPATH")

ROOT=${1}
FILE=${2}
ENABLEFILE=${3}
COMMONFILE=${4}
LEAFFILE=${5}
NODEFILE=${6}

# Extract the dependencies for the file.
DFSN=`cat ${ROOT}/${FILE} | grep -E M4_NEEDS | sed "s/M4_NEEDS(//" | sed "s/)dnl//"`
DFSI=`cat ${ROOT}/${FILE} | grep -E M4_INCLUDEOPT | sed "s/M4_INCLUDEOPT(//" | sed "s/)dnl//"`
DFST=`echo "${DFSN} ${DFSI}" | sed "s/^\s*//"`

classname() {
    STRING=`echo "$2" | sed "s/\//\./g" | sed "s/\.js//" | sed "s/\\(\\S\\S*\\.\\)*//" | sed "s/.*_named_//"`
    eval "$1=\"\$STRING\""
}

DFS=""
for DFT in ${DFST};
do
    classname DF ${DFT}
    DFS="${DFS} ${DF}"
done
DFS=`echo "${DFS}" | tr " " "\n" | sort | tr "\n" " " | sed -e "s/^[[:space:]]*//"`

# Generate a Makefile rule.

classname TARGET ${FILE}

ENABLESTRING="@./tools/enable ${FILE} ${ENABLEFILE}"

PATTERN="\\(\\(test_verificatum\\)\\|\\(arithm\\)\\|\\(test_arithm\\)\\|\\(crypto\\)\\|\\(test_crypto\\)\\|\\(ECqPGroup\\)\\|\\(curves\\)\\|\\(ECqPGroup\\)\\|\\(groups\\)\\)"

if test x"${DFS}" = x;
then
    printf "%s:+" ${TARGET} >> ${LEAFFILE}
    printf "\t${ENABLESTRING}\n" >> ${LEAFFILE}
else
    MATCH_LEN=`printf ${TARGET} | sed "s/${PATTERN}.*//" | wc -c`
    if test ${MATCH_LEN} = 0;
    then
        FILE=${COMMONFILE}
    else
        FILE=${NODEFILE}
    fi
    printf "%s:" ${TARGET} >> ${FILE}
    for DF in ${DFS};
    do
        printf " %s" ${DF} >> ${FILE}
    done
    printf "+\t${ENABLESTRING}\n" >> ${FILE}
fi

