#!/bin/sh

# Copyright 2008-2019 Douglas Wikstrom
#
# This file is part of Verificatum JavaScript Cryptographic library
# (VJSC).
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use, copy,
# modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

SCRIPTPATH=$(readlink -f "$0")
SCRIPTDIR=$(dirname "$SCRIPTPATH")

TMP_DIR=${1}
ROOT=${2}
RAWENABLEFILE=${3}
ENABLEFILE=${4}
TESTENABLEFILE=${5}
MAKEFILE=${6}
COMMONFILE=${TMP_DIR}/common
LEAFFILE=${TMP_DIR}/leaves
NODEFILE=${TMP_DIR}/nodes

rm -f ${MAKEFILE}
rm -f ${COMMONFILE}
rm -f ${LEAFFILE}
rm -f ${NODEFILE}

${SCRIPTDIR}/getneeds ${TMP_DIR} ${ROOT} ${TMP_DIR}/needfiles
NEEDFILES=`cat ${TMP_DIR}/needfiles`
NEEDFILES="${NEEDFILES} verificatum/verificatum.js verificatum/test_verificatum.js"

for NEEDFILE in ${NEEDFILES};
do
    ${SCRIPTDIR}/getrule ${ROOT} ${NEEDFILE} ${RAWENABLEFILE} ${COMMONFILE} ${LEAFFILE} ${NODEFILE}
done

printf "#\n# Main targets.\n" >> ${MAKEFILE}
printf "#\n# The fact that you must include at least one concrete implementation\n" >> ${MAKEFILE}
printf "# is not captured here. You must only edit the dependencies.\n#\n" >> ${MAKEFILE}

printf "${ENABLEFILE}: | delete_main_targets verificatum\n" >> ${MAKEFILE}
printf "\t@cat ${RAWENABLEFILE} | sort > ${ENABLEFILE}\n" >> ${MAKEFILE}
printf "\t@echo \"Generate enabling M4 macros in ${ENABLEFILE}.\"\n" >> ${MAKEFILE}

printf "${TESTENABLEFILE}: | delete_main_targets test_verificatum\n" >> ${MAKEFILE}
printf "\t@cat ${RAWENABLEFILE} | sort > ${TESTENABLEFILE}\n" >> ${MAKEFILE}
printf "\t@echo \"Generate enabling M4 macros in ${TESTENABLEFILE}.\"\n" >> ${MAKEFILE}

printf "#\n# Commonly modified targets.\n#\n" >> ${MAKEFILE}
cat ${COMMONFILE} | grep -v "test_" | sort | uniq | tr "+" "\n" >> ${MAKEFILE}
printf "\n" >> ${MAKEFILE}
cat ${COMMONFILE} | grep "test_" | sort | uniq | tr "+" "\n" >> ${MAKEFILE}

printf "\n#\n# Other modifiable targets:\n#\n" >> ${MAKEFILE}
cat ${NODEFILE} | grep -v "test_" | sort | uniq | tr "+" "\n" >> ${MAKEFILE}
printf "\n" >> ${MAKEFILE}
cat ${NODEFILE} | grep "test_" | sort | uniq | tr "+" "\n" >> ${MAKEFILE}

printf "\n#\n# DO NOT EDIT THE FOLLOWING ENTRIES!\n#\n" >> ${MAKEFILE}
cat ${LEAFFILE} | sort | uniq | tr "+" "\n\n" >> ${MAKEFILE}

printf "#\n# This is a hack to get something more robust than .PHONY.\n#\n" >> ${MAKEFILE}
printf "delete_main_targets:\n" >> ${MAKEFILE}
printf "\t@rm -f ${RAWENABLEFILE}\n" >> ${MAKEFILE}
